apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testgo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgo
  template:
    metadata:
      labels:
        app: testgo
    spec:
      containers:
       - name: testgo-container
         image: elmashad/testgo:v1
      ports:
        - containerPort: 8080
          name: http
      env:
        - name: APP_CONFIG
          value: '{
            "app": {
              "host": "localhost",
              "port": "8080",
              "enabled": true
            },
            "mongodb": {
              "name": "mongodb",
              "driver": "mongodb",
              "dsn": "mongodb://melting-clam-mongodb.default.svc.cluster.local:27017",
              "host": "localhost",
              "port": "27017",
              "username": "",
              "password": "",
              "db_name": "movie_api",
              "options": {}
            }
          }'